/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_panjq_opencv_alg_ImagePro */

#ifndef _Included_com_panjq_opencv_alg_ImagePro
#define _Included_com_panjq_opencv_alg_ImagePro
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_panjq_opencv_alg_ImagePro
 * Method:    ImageBlur
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_panjq_opencv_alg_ImagePro_ImageBlur
  (JNIEnv *, jobject, jintArray, jint, jint);

/*
 * Class:     com_panjq_opencv_alg_ImagePro
 * Method:    ImageProJNI
 * Signature: (Lcom/panjq/opencv/alg/ImageData;)Lcom/panjq/opencv/alg/ImageData;
 */
JNIEXPORT jobject JNICALL Java_com_panjq_opencv_alg_ImagePro_ImageProJNI
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
